apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.releasename }}-{{ .Values.myscret.myreposecretname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfig | toJson | b64enc | quote }}